### ISSUE TITLE
Figma: Tela de Cadastro de Disciplina

### ISSUE THREAD

**Issue by niltonjr80** [ivpinheiro/react-native-app#1]
- [x] Criar mockup com campo de texto para o nome da disciplina.
   - [x] Criar mockup com dropdown/seletor para o dia da semana.
   - [x] Criar mockup com campo de texto/seletor para o horário.
   - [x] Adicionar botões para adicionar/remover aulas.
   - [x] Adicionar barra de navegação fixa no rodapé.

**Comment by erika-hortencia** [comment]
- [x] Para os dias da semana, optei por um seletor ao invés de dropdown pois algumas aulas acontecem em mais de um dia
- [x] O botão de remover aula, acho que ficaria melhor dentro da página da própria disciplina, por isso incluí aqui apenas o botão de adicionar
- [x] Para o campo de horário foi utilizado um campo de texto ao invés de seletor para facilitar input do usuário 

![image](https://github.com/ivpinheiro/react-native-app/assets/50000777/dcc4cf7b-33d7-487b-abdb-323a78f82bba)
