### ISSUE TITLE
Figma:  Tela de Dashboard

### ISSUE THREAD

**Issue by niltonjr80** [ivpinheiro/react-native-app#2]
- [x] Criar mockup com lista das disciplinas agendadas para o dia atual.
   - [x] Adicionar botões "Presente" e "Ausente" para cada disciplina.
   - [x] Adicionar botão para acessar o histórico de faltas.
   - [x] Adicionar barra de navegação fixa no rodapé.

**Comment by erika-hortencia** [comment]
- [x] Lista de disciplinas do dia
![image](https://github.com/ivpinheiro/react-native-app/assets/50000777/334fe4ad-7b81-4e78-ae4c-d7ad30b74f8a)

- [x] Botões de presente/ausente
![image](https://github.com/ivpinheiro/react-native-app/assets/50000777/cf0d336e-bfec-4c81-8f3b-bbd889e6d216)

- [x] Navegação para o histórico de faltas da disciplina
- [x] Barra no rodapé
