### ISSUE TITLE
Figma:  Tela de Histórico de Faltas

### ISSUE THREAD

**Issue by niltonjr80** [ivpinheiro/react-native-app#3]
- [x] Criar mockup com filtros por disciplina e período.
   - [x] Criar mockup com lista de faltas registradas (data, disciplina e status).
   - [x] Adicionar barra de navegação fixa no rodapé.

**Comment by erika-hortencia** [comment]
- [x] Filtro por disciplina e período implementado
- [x] Mockup de presença implementado
- [x] Adicionado um botão de "Detalhes" para levar à página da disciplina selecionada

![image](https://github.com/ivpinheiro/react-native-app/assets/50000777/4af1608a-4c9d-4a30-a9b0-0a3012694963)
