### ISSUE TITLE
Figma:  Tela de Perfil

### ISSUE THREAD

**Issue by niltonjr80** [ivpinheiro/react-native-app#4]
- [x] Criar mockup com campo de texto para o nome do usuário.
   - [x] Criar mockup com campo de texto para o email do usuário (não editável).
   - [x] Criar mockup com campo de texto para a senha.
   - [x] Adicionar barra de navegação fixa no rodapé.

**Comment by erika-hortencia** [comment]
Tela de perfil do usuário finalizada:

![image](https://github.com/ivpinheiro/react-native-app/assets/50000777/1a7add91-6227-4c3b-b1b3-5fe52467cb83)

Disponível [aqui](https://www.figma.com/design/iUci6mk0ivtk0q68bBEETS/Class-Attendance-Tracker?m=dev&node-id=6-7&t=xWBg6SgvLImrc4ur-1)
